config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  get 'projects/index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E1m5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">


    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Inicio",  root_path, :class => "nav-link"%>
      <%= link_to "Proyectos",  projects_index_path, :class => "nav-link" %>
      <%= link_to "Contacto",  contact_index_path, :class => "nav-link"%>
    </div>
  </div>
</nav>


  <div class="container"
 


   <%= yield %>

  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


  </body>
</html>

app/views/projects/index.html.erb
<h1>Proyectos realizados</h1>


<div class="card" style="width: 18rem;">
<%= image_tag("rails01.jpg") %>
  <div class="card-body">
    <h5 class="card-title">Proyecto Tweeter</h5>
    <p class="card-text">Inicio del proyecto Tweeter - Inforcap</p>
    <a href="https://github.com/gcalquin/PruebaM5" class="btn btn-primary">Ir al proyecto</a>
  </div>
</div>

<br><br>

<div class="card" style="width: 18rem;">
<%= image_tag("rails02.jpg") %>
  <div class="card-body">
    <h5 class="card-title"Proyecto 3</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<br>

<div class="card" style="width: 18rem;">
<%= image_tag("rails03.jpg") %>
  <div class="card-body">
    <h5 class="card-title">Proyecto 3</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>